--- #YAML:1.0
name:         Hook-Filter
abstract:     A runtime subroutine call firewall
version:      0.04
author:
    - Erwan Lemonnier <erwan@cpan.org>
license:      perl
distribution_type: module
requires:
    Module::Pluggable              2.2
    File::Spec                     0.86
build_requires:
    Test::More:                    0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
ressources:
    license: http://dev.perl.org/licenses/
    homepage: http://sourceforge.net/projects/hook-filter
    bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Hook-Filter
    repository: https://sourceforge.net/cvs/?group_id=196433
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
